_BASE_: zegformer_R50_bs32_60k_vit16_coco-stuff.yaml
MODEL:
#  BACKBONE:
#    NAME: "build_resnet_deeplab_backbone"
  WEIGHTS: "R-101.pkl"
  META_ARCHITECTURE: "MaskFormer"
  RESNETS:
    DEPTH: 101
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
