_BASE_: Base-COCOStuff-171.yaml
MODEL:
  META_ARCHITECTURE: "MaskFormer"
  SEM_SEG_HEAD:
    NAME: "ZegFormerHead"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    IGNORE_VALUE: 255
    NUM_CLASSES: 156
    COMMON_STRIDE: 4  # not used, hard-coded
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    TRAIN_CLASS_JSON: "/mnt/server14_hard1/msson/datasets/zs3_datasets/coco/coco_stuff/split/seen_classnames.json"
    TEST_CLASS_JSON: "/mnt/server14_hard1/msson/datasets/zs3_datasets/coco/coco_stuff/split/seen_classnames.json"
    CLIP_PRETRAINED: "ViT-B/16"
    #    CLIP_CLASSIFICATION: True
  PROMPT_ENSEMBLE_TYPE: "imagenet_select"
  MASK_FORMER:
    TRANSFORMER_IN_FEATURE: "res5"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    DICE_WEIGHT: 1.0
    MASK_WEIGHT: 20.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.1
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    DEC_LAYERS: 6
    PRE_NORM: False
SOLVER:
  IMS_PER_BATCH: 32
#  BASE_LR: 0.0001
  MAX_ITER: 60000
  AMP:
    ENABLED: True
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
#  NUM_WORKERS: 4
  NUM_WORKERS: 8
CUDNN_BENCHMARK: True
